version: '3'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - mariadb
    ports:
      - "8089:80"
    volumes:
      - ./src:/var/www/html
    env_file:
      - .env

  mariadb:
      container_name: mariadb
      environment:
        - MYSQL_DATABASE=app_db
        - MYSQL_USER=app_admin
        - MYSQL_PASSWORD=app_admin
        - MYSQL_ROOT_PASSWORD=app_admin
      image: mariadb:10.0.21
      ports:
        - "3307:3307"

  phpmyadmin:
      container_name: phpmyadmin
      image: phpmyadmin
      restart: always
      expose:
        - "40001"
      ports:
        - "40001:80"
      environment:
        - PMA_HOST=mariadb
        - PMA_PORT=3306

volumes:
    app_data:
    mariadb_data: